package com.bank.bian.liquiditymanagement;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Liquidity Management
 *
 * Business Area:      Risk and Compliance
 * Business Domain:    Market and Operational Risk
 * Functional Pattern: Manage
 * Asset Type:         Liquidity Position
 * Control Record:     Liquidity Position Management Plan
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Liquidity Management — BIAN Semantic API")
                .description("Service Domain 'Liquidity Management' (Manage pattern) "
                        + "operating on the 'Liquidity Position Management Plan' control record.")
                .version("0.1.0"));
    }
}
