apiVersion: v2
name: sd-liquidity-management
description: "BIAN Service Domain: Liquidity Management (Manage pattern, Risk and Compliance)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - manage
annotations:
  bian/business-area: "Risk and Compliance"
  bian/business-domain: "Market and Operational Risk"
  bian/asset-type: "Liquidity Position"
  bian/control-record: "Liquidity Position Management Plan"
